const properties=[
 {id:1,title:'Apartamento Aurora',location:'Lourdes, Belo Horizonte',type:'Apartamento',deal:'Comprar',price:1280000,label:'DESTAQUE',beds:3,baths:3,area:142,images:['https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=900&q=85','https://images.unsplash.com/photo-1600566753051-f0b89df2dd90?auto=format&fit=crop&w=900&q=85'],description:'Apartamento iluminado, com living integrado, varanda generosa e acabamento contemporâneo. A poucos passos dos melhores restaurantes de Lourdes.'},
 {id:2,title:'Casa Bosque da Serra',location:'Vila da Serra, Nova Lima',type:'Casa',deal:'Comprar',price:2450000,label:'EXCLUSIVO',beds:4,baths:5,area:310,images:['https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=900&q=85','https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=900&q=85'],description:'Arquitetura elegante em um terreno cercado de verde. Piscina, espaço gourmet, quatro suítes e total privacidade.'},
 {id:3,title:'Penthouse Horizonte',location:'Funcionários, Belo Horizonte',type:'Cobertura',deal:'Comprar',price:3100000,label:'NOVO',beds:4,baths:4,area:265,images:['https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=900&q=85','https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=900&q=85'],description:'Cobertura com vista panorâmica, interiores sofisticados, piscina privativa e localização privilegiada.'},
 {id:4,title:'Loft Savassi 81',location:'Savassi, Belo Horizonte',type:'Apartamento',deal:'Alugar',price:6800,label:'MOBILIADO',beds:1,baths:1,area:68,images:['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=900&q=85'],description:'Loft mobiliado com design autoral, automação e toda a conveniência da Savassi ao redor.'},
 {id:5,title:'Casa Jardim das Águas',location:'Belvedere, Belo Horizonte',type:'Casa',deal:'Comprar',price:2890000,label:'OPORTUNIDADE',beds:4,baths:5,area:390,images:['https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=900&q=85'],description:'Casa ampla com jardim, piscina aquecida e uma área social feita para receber bem.'},
 {id:6,title:'Studio Praça da Liberdade',location:'Lourdes, Belo Horizonte',type:'Apartamento',deal:'Alugar',price:4200,label:'NOVO',beds:1,baths:1,area:45,images:['https://images.unsplash.com/photo-1600210491369-e753d80a41f3?auto=format&fit=crop&w=900&q=85'],description:'Compacto, elegante e funcional, a poucos metros da Praça da Liberdade.'}
];
let favorites=new Set(JSON.parse(localStorage.getItem('avFavorites')||'[]'));let currentDeal='Comprar';let heroIndex=0;
const grid=document.querySelector('#propertyGrid'),money=v=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0});
function render(list=properties.slice(0,3)){grid.innerHTML=list.map(p=>`<article class="property-card"><div class="property-image" data-detail="${p.id}" style="background-image:url('${p.images[0]}')"><span class="tag ${p.label==='NOVO'?'gold':''}">${p.label}</span><button class="heart ${favorites.has(p.id)?'active':''}" data-favorite="${p.id}" aria-label="Favoritar">${favorites.has(p.id)?'♥':'♡'}</button><span class="image-count">▧ ${p.images.length}</span></div><div class="card-body"><p class="card-location">⌖ ${p.location}</p><h3>${p.title}</h3><div class="card-features"><span>⌂ ${p.beds} quartos</span><span>♢ ${p.baths} banhos</span><span>□ ${p.area} m²</span></div><div class="card-price"><div><small>${p.deal==='Alugar'?'ALUGUEL MENSAL':'VALOR DO IMÓVEL'}</small><strong>${money(p.price)}${p.deal==='Alugar'?'<small>/mês</small>':''}</strong></div><button data-detail="${p.id}" aria-label="Ver detalhes">→</button></div></div></article>`).join('');document.querySelector('#emptyState').hidden=list.length>0}
function updateFavorites(){localStorage.setItem('avFavorites',JSON.stringify([...favorites]));document.querySelector('#favoriteCount').textContent=favorites.size}
render();updateFavorites();
document.addEventListener('click',e=>{const fav=e.target.closest('[data-favorite]');if(fav){e.stopPropagation();const id=+fav.dataset.favorite;favorites.has(id)?favorites.delete(id):favorites.add(id);updateFavorites();applyCurrentFilters();showToast(favorites.has(id)?'Imóvel salvo nos favoritos':'Removido dos favoritos');return}const detail=e.target.closest('[data-detail]');if(detail)openProperty(+detail.dataset.detail)});
function applyCurrentFilters(){const term=document.querySelector('#locationSearch').value.toLowerCase(),type=document.querySelector('#typeSearch').value,max=+document.querySelector('#priceSearch').value;const filtered=properties.filter(p=>p.deal===currentDeal&&(!term||(p.location+' '+p.title).toLowerCase().includes(term))&&(!type||p.type===type)&&(!max||p.price<=max));render(filtered)}
document.querySelector('#propertySearch').addEventListener('submit',e=>{e.preventDefault();applyCurrentFilters();document.querySelector('#imoveis').scrollIntoView();});
document.querySelectorAll('.deal-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.deal-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentDeal=b.dataset.deal});
document.querySelectorAll('.filter-chips button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter-chips button').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.filter==='Todos'?properties.slice(0,3):properties.filter(p=>p.type===b.dataset.filter).slice(0,3))});
document.querySelector('#showAll').onclick=()=>render(properties);
function openProperty(id){const p=properties.find(x=>x.id===id),modal=document.querySelector('#propertyModal');document.querySelector('#propertyModalContent').innerHTML=`<div class="detail-gallery" style="background-image:url('${p.images[0]}')"><span class="tag">${p.label}</span></div><div class="detail-info"><span class="eyebrow">${p.type.toUpperCase()} • ${p.deal.toUpperCase()}</span><h2>${p.title}</h2><p>⌖ ${p.location}</p><div class="card-features"><span>${p.beds} quartos</span><span>${p.baths} banheiros</span><span>${p.area} m²</span></div><p>${p.description}</p><div class="card-price"><strong>${money(p.price)}</strong><button class="btn btn-gold contact-trigger">Tenho interesse →</button></div></div>`;openModal(modal)}
function openModal(m){m.classList.add('open');m.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}function closeModal(m){m.classList.remove('open');m.setAttribute('aria-hidden','true');document.body.style.overflow=''}
document.querySelectorAll('.modal-close').forEach(b=>b.onclick=()=>closeModal(b.closest('.modal')));document.querySelectorAll('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModal(m)}));
document.addEventListener('click',e=>{if(e.target.closest('.contact-trigger')){document.querySelectorAll('.modal.open').forEach(closeModal);openModal(document.querySelector('#contactModal'))}});
document.addEventListener('click',e=>{if(e.target.closest('.vic-contact')){document.querySelectorAll('.modal.open').forEach(closeModal);openModal(document.querySelector('#contactModal'));document.querySelector('#interestSelect').value='Apartamento na planta — VIC Engenharia'}});
document.querySelector('#contactForm').onsubmit=e=>{e.preventDefault();closeModal(document.querySelector('#contactModal'));showToast('Recebemos seus dados! Em breve entraremos em contato.');e.target.reset()};
document.querySelector('.favorites-trigger').onclick=()=>{const list=properties.filter(p=>favorites.has(p.id));render(list);document.querySelector('#imoveis').scrollIntoView();showToast(list.length?`${list.length} imóvel(is) favorito(s)`:'Você ainda não salvou imóveis')};
setInterval(()=>{heroIndex=(heroIndex+1)%3;document.querySelectorAll('.hero-slide').forEach((s,i)=>s.classList.toggle('active',i===heroIndex));document.querySelectorAll('.hero-dots button').forEach((s,i)=>s.classList.toggle('active',i===heroIndex))},5000);
document.querySelectorAll('.hero-dots button').forEach((b,i)=>b.onclick=()=>{heroIndex=i;document.querySelectorAll('.hero-slide').forEach((s,j)=>s.classList.toggle('active',j===i));document.querySelectorAll('.hero-dots button').forEach((s,j)=>s.classList.toggle('active',j===i))});
document.querySelector('.menu-toggle').onclick=()=>document.querySelector('#mainNav').classList.toggle('open');document.querySelectorAll('#mainNav a').forEach(a=>a.onclick=()=>document.querySelector('#mainNav').classList.remove('open'));
const admin=document.querySelector('#adminModal');document.querySelector('.admin-trigger').onclick=()=>{renderAdmin('dashboard');openModal(admin)};document.querySelectorAll('[data-admin]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-admin]').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderAdmin(b.dataset.admin)});
function renderAdmin(view){const c=document.querySelector('#adminContent');if(view==='dashboard')c.innerHTML=`<div class="admin-title"><div><span class="eyebrow">PAINEL ADMINISTRATIVO</span><h2>Olá, Wellington!</h2></div><button class="btn btn-gold" id="newProperty">+ Novo anúncio</button></div><div class="admin-metrics"><div class="metric"><span>IMÓVEIS ATIVOS</span><strong>${properties.length}</strong></div><div class="metric"><span>CONTATOS NO MÊS</span><strong>24</strong></div><div class="metric"><span>VISUALIZAÇÕES</span><strong>1.842</strong></div></div><div class="admin-list"><div class="admin-row"><b>Imóvel</b><b>Valor</b><b>Status</b><b>Ações</b></div>${properties.slice(0,4).map(p=>`<div class="admin-row"><span><img src="${p.images[0]}">${p.title}</span><span>${money(p.price)}</span><span><i class="status">PUBLICADO</i></span><button>•••</button></div>`).join('')}</div>`;else if(view==='properties')c.innerHTML=`<div class="admin-title"><h2>Gerenciar imóveis</h2><button class="btn btn-gold" id="newProperty">+ Novo anúncio</button></div><div class="admin-list">${properties.map(p=>`<div class="admin-row"><span><img src="${p.images[0]}">${p.title}</span><span>${p.type}</span><span><i class="status">PUBLICADO</i></span><button>Editar</button></div>`).join('')}</div>`;else c.innerHTML=`<div class="admin-title"><h2>Contatos recebidos</h2></div><div class="admin-list">${['Ana Paula — Apartamento Aurora','Carlos Mendes — Casa Bosque da Serra','Rafael Lima — Reserva das Oliveiras'].map((x,i)=>`<div class="admin-row"><b>${x}</b><span>${i+1} dia(s) atrás</span><span><i class="status">NOVO</i></span><button>Responder</button></div>`).join('')}</div>`;const np=document.querySelector('#newProperty');if(np)np.onclick=()=>showNewPropertyForm()}
function showNewPropertyForm(){document.querySelector('#adminContent').innerHTML=`<div class="admin-title"><h2>Criar novo anúncio</h2></div><div class="form-card" style="padding:0;max-width:600px"><form id="newPropertyForm"><label>Título<input required placeholder="Ex.: Apartamento Vila Nova"></label><label>Localização<input required placeholder="Bairro, cidade"></label><label>Tipo<select><option>Apartamento</option><option>Casa</option><option>Cobertura</option><option>Comercial</option></select></label><label>Valor<input required type="number" placeholder="R$ 0,00"></label><label>Descrição<input placeholder="Principais diferenciais do imóvel"></label><button class="btn btn-gold" type="submit">Publicar anúncio →</button></form></div>`;document.querySelector('#newPropertyForm').onsubmit=e=>{e.preventDefault();renderAdmin('properties');showToast('Anúncio publicado com sucesso!')}}
function showToast(t){const el=document.querySelector('#toast');el.textContent=t;el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),3200)}
const plantTrack=document.querySelector('#plantCards');document.querySelector('#plantNext').onclick=()=>plantTrack.scrollBy({left:300,behavior:'smooth'});document.querySelector('#plantPrev').onclick=()=>plantTrack.scrollBy({left:-300,behavior:'smooth'});
