const properties=[
 {id:254,code:'WS-254',title:'Apartamento Aurora',city:'Belo Horizonte',district:'Lourdes',location:'Lourdes, Belo Horizonte',type:'Apartamento',deal:'Comprar',price:1280000,condo:890,iptu:210,label:'Destaque',beds:3,suites:1,baths:3,garage:2,area:142,builtArea:142,condominium:'Sim',pool:false,grill:true,pet:true,launch:false,plant:false,status:'Publicado',broker:'Wellington Nascimento',video:'Vídeo de apresentação do imóvel',tour:'Tour virtual 360° disponível',doc:'Matrícula, IPTU e certidões em análise preventiva.',features:['Varanda gourmet','Sala integrada','Elevador','Portaria 24h','Churrasqueira'],images:['https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1100&q=85','https://images.unsplash.com/photo-1600566753051-f0b89df2dd90?auto=format&fit=crop&w=1100&q=85','https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1100&q=85'],description:'Apartamento iluminado, com living integrado, varanda generosa e acabamento contemporâneo. A poucos passos dos melhores restaurantes de Lourdes.'},
 {id:301,code:'WS-301',title:'Casa Bosque da Serra',city:'Nova Lima',district:'Vila da Serra',location:'Vila da Serra, Nova Lima',type:'Casa',deal:'Comprar',price:2450000,condo:0,iptu:480,label:'Exclusivo',beds:4,suites:4,baths:5,garage:4,area:520,builtArea:310,condominium:'Não',pool:true,grill:true,pet:true,launch:false,plant:false,status:'Publicado',broker:'Wellington Nascimento',video:'Vídeo cinematográfico da casa',tour:'Tour 360° dos ambientes sociais',doc:'Documentação pronta para escritura.',features:['Piscina','Espaço gourmet','Jardim','Suítes amplas','Vista definitiva'],images:['https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1100&q=85','https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1100&q=85','https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1100&q=85'],description:'Arquitetura elegante em um terreno cercado de verde. Piscina, espaço gourmet, quatro suítes e total privacidade.'},
 {id:418,code:'WS-418',title:'Penthouse Horizonte',city:'Belo Horizonte',district:'Funcionários',location:'Funcionários, Belo Horizonte',type:'Cobertura',deal:'Comprar',price:3100000,condo:1450,iptu:620,label:'Lançamento',beds:4,suites:2,baths:4,garage:3,area:265,builtArea:265,condominium:'Sim',pool:true,grill:true,pet:true,launch:true,plant:false,status:'Publicado',broker:'Wellington Nascimento',video:'Vídeo com drone e interiores',tour:'Tour 360° na cobertura',doc:'Memorial descritivo e registro do empreendimento.',features:['Vista panorâmica','Piscina privativa','Área gourmet','Alto padrão','Fechadura digital'],images:['https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1100&q=85','https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1100&q=85','https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1100&q=85'],description:'Cobertura com vista panorâmica, interiores sofisticados, piscina privativa e localização privilegiada.'},
 {id:512,code:'WS-512',title:'Loft Savassi 81',city:'Belo Horizonte',district:'Savassi',location:'Savassi, Belo Horizonte',type:'Apartamento',deal:'Alugar',price:6800,condo:720,iptu:160,label:'Oportunidade',beds:1,suites:1,baths:1,garage:1,area:68,builtArea:68,condominium:'Sim',pool:false,grill:false,pet:true,launch:false,plant:false,status:'Publicado',broker:'Wellington Nascimento',video:'Vídeo curto para locação',tour:'Tour 360° do loft',doc:'Contrato, vistoria e garantia locatícia.',features:['Mobiliado','Automação','Academia','Coworking','Aceita pet'],images:['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1100&q=85','https://images.unsplash.com/photo-1600210491369-e753d80a41f3?auto=format&fit=crop&w=1100&q=85'],description:'Loft mobiliado com design autoral, automação e toda a conveniência da Savassi ao redor.'},
 {id:633,code:'WS-633',title:'Casa Jardim das Águas',city:'Belo Horizonte',district:'Belvedere',location:'Belvedere, Belo Horizonte',type:'Casa',deal:'Comprar',price:2890000,condo:0,iptu:510,label:'Oportunidade',beds:4,suites:3,baths:5,garage:4,area:620,builtArea:390,condominium:'Não',pool:true,grill:true,pet:true,launch:false,plant:false,status:'Publicado',broker:'Wellington Nascimento',video:'Vídeo da área de lazer',tour:'Tour 360° externo e interno',doc:'IPTU, matrícula e habite-se disponíveis.',features:['Piscina aquecida','Jardim','Home office','Área gourmet','Energia solar'],images:['https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1100&q=85','https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1100&q=85'],description:'Casa ampla com jardim, piscina aquecida e uma área social feita para receber bem.'},
 {id:710,code:'WS-710',title:'Studio Praça da Liberdade',city:'Belo Horizonte',district:'Lourdes',location:'Lourdes, Belo Horizonte',type:'Apartamento',deal:'Alugar',price:4200,condo:520,iptu:120,label:'Destaque',beds:1,suites:0,baths:1,garage:1,area:45,builtArea:45,condominium:'Sim',pool:false,grill:false,pet:false,launch:false,plant:false,status:'Publicado',broker:'Wellington Nascimento',video:'Vídeo tour do studio',tour:'Tour 360° disponível',doc:'Documentação locatícia simplificada.',features:['Compacto','Mobiliado','Portaria','Próximo à praça','Garagem'],images:['https://images.unsplash.com/photo-1600210491369-e753d80a41f3?auto=format&fit=crop&w=1100&q=85','https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1100&q=85'],description:'Compacto, elegante e funcional, a poucos metros da Praça da Liberdade.'},
 {id:811,code:'VIC-811',title:'Viva Parque Residence — VIC',city:'Contagem',district:'Cabral',location:'Cabral, Contagem',type:'Apartamento',deal:'Na planta',price:249000,condo:320,iptu:70,label:'Lançamento',beds:2,suites:0,baths:1,garage:1,area:44,builtArea:44,condominium:'Sim',pool:true,grill:true,pet:true,launch:true,plant:true,status:'Publicado',broker:'Wellington Nascimento',video:'Vídeo do empreendimento VIC',tour:'Tour virtual do decorado',doc:'Memorial de incorporação e plantas.',features:['Na planta','Lazer completo','FGTS','Minha Casa Minha Vida','Entrada facilitada'],images:['https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1100&q=85','https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1100&q=85'],description:'Apartamento na planta da VIC Engenharia com lazer completo, plantas inteligentes e possibilidade de financiamento habitacional.'},
 {id:902,code:'WS-902',title:'Terreno Comercial Avenida Central',city:'Osasco',district:'Centro',location:'Centro, Osasco',type:'Terreno',deal:'Comprar',price:860000,condo:0,iptu:300,label:'Exclusivo',beds:0,suites:0,baths:0,garage:0,area:480,builtArea:0,condominium:'Não',pool:false,grill:false,pet:false,launch:false,plant:false,status:'Publicado',broker:'Wellington Nascimento',video:'Vídeo da localização',tour:'Tour 360° do entorno',doc:'Zoneamento e matrícula disponíveis.',features:['Comercial','Esquina','Alto fluxo','Documentação ok','Boa testada'],images:['https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1100&q=85','https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1100&q=85'],description:'Terreno com excelente visibilidade para ponto comercial, incorporação ou investimento.'}
];

const money=v=>Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0});
const phone='5531999999999';
let favorites=new Set(JSON.parse(localStorage.getItem('wsFavorites')||'[]'));
let currentDeal='Comprar', currentList=[...properties], currentPage=1, pageSize=6, heroIndex=0;
const grid=document.querySelector('#propertyGrid');

function saveFavorites(){localStorage.setItem('wsFavorites',JSON.stringify([...favorites]));document.querySelector('#favoriteCount').textContent=favorites.size}
function whatsappText(p){return `https://wa.me/${phone}?text=${encodeURIComponent(`Olá! Tenho interesse no imóvel código ${p.code} - ${p.title}.`)}`}
function render(list=currentList,page=1){
 currentList=list;currentPage=page;
 const start=(page-1)*pageSize, items=list.slice(start,start+pageSize);
 grid.innerHTML=items.map(p=>`<article class="property-card">
  <div class="property-image" data-detail="${p.id}" style="background-image:url('${p.images[0]}')">
   <span class="tag ${p.label==='Lançamento'?'gold':''}">${p.label}</span>
   <button class="heart ${favorites.has(p.id)?'active':''}" data-favorite="${p.id}" aria-label="Favoritar">${favorites.has(p.id)?'♥':'♡'}</button>
   <span class="image-count">▧ ${p.images.length}</span>
  </div>
  <div class="card-body">
   <p class="card-location">⌖ ${p.location} • ${p.code}</p>
   <h3>${p.title}</h3>
   <div class="card-features"><span>⌂ ${p.beds} dorm.</span><span>♢ ${p.suites} suíte(s)</span><span>☷ ${p.baths} banh.</span><span>▣ ${p.garage} vaga(s)</span><span>□ ${p.area} m²</span></div>
   <div class="card-price"><div><small>${p.deal==='Alugar'?'ALUGUEL MENSAL':'VALOR DO IMÓVEL'}</small><strong>${money(p.price)}${p.deal==='Alugar'?'<small>/mês</small>':''}</strong></div><div class="card-actions"><a href="${whatsappText(p)}" target="_blank" rel="noopener" aria-label="WhatsApp">☘</a><button data-share="${p.id}" aria-label="Compartilhar">↗</button><button data-detail="${p.id}" aria-label="Ver detalhes">→</button></div></div>
  </div>
 </article>`).join('');
 document.querySelector('#emptyState').hidden=list.length>0;
 renderPagination(list.length,page);
}
function renderPagination(total,page){const pages=Math.ceil(total/pageSize), el=document.querySelector('#pagination');el.innerHTML=pages>1?Array.from({length:pages},(_,i)=>`<button class="${page===i+1?'active':''}" data-page="${i+1}">${i+1}</button>`).join(''):''}
function applyCurrentFilters(){
 const city=(document.querySelector('#filterCity')?.value||document.querySelector('#citySearch')?.value||'').toLowerCase();
 const district=(document.querySelector('#filterDistrict')?.value||document.querySelector('#districtSearch')?.value||'').toLowerCase();
 const type=document.querySelector('#filterType')?.value||document.querySelector('#typeSearch')?.value||'';
 const max=+(document.querySelector('#filterPrice')?.value||document.querySelector('#priceSearch')?.value||0);
 const beds=+(document.querySelector('#filterBeds')?.value||0),suites=+(document.querySelector('#filterSuites')?.value||0),baths=+(document.querySelector('#filterBaths')?.value||0),garage=+(document.querySelector('#filterGarage')?.value||0),area=+(document.querySelector('#filterArea')?.value||0);
 const condo=document.querySelector('#filterCondo')?.value||'',pool=document.querySelector('#filterPool')?.checked,grill=document.querySelector('#filterGrill')?.checked,pet=document.querySelector('#filterPet')?.checked,launch=document.querySelector('#filterLaunch')?.checked,plant=document.querySelector('#filterPlant')?.checked;
 const list=properties.filter(p=>(currentDeal==='Todos'||p.deal===currentDeal||currentDeal===p.label)&&(!city||p.city.toLowerCase().includes(city))&&(!district||p.district.toLowerCase().includes(district))&&(!type||p.type===type)&&(!max||p.price<=max)&&(!beds||p.beds>=beds)&&(!suites||p.suites>=suites)&&(!baths||p.baths>=baths)&&(!garage||p.garage>=garage)&&(!area||p.area>=area)&&(!condo||p.condominium===condo)&&(!pool||p.pool)&&(!grill||p.grill)&&(!pet||p.pet)&&(!launch||p.launch)&&(!plant||p.plant));
 render(list,1);
}
function openModal(m){m.classList.add('open');m.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeModal(m){m.classList.remove('open');m.setAttribute('aria-hidden','true');document.body.style.overflow=''}
function openProperty(id){
 const p=properties.find(x=>x.id===id),modal=document.querySelector('#propertyModal');
 document.querySelector('#propertyModalContent').innerHTML=`<div class="detail-hero"><div class="detail-gallery" style="background-image:url('${p.images[0]}')"><span class="tag">${p.label}</span></div><div class="detail-thumbs">${p.images.slice(1).map(img=>`<div class="detail-thumb" style="background-image:url('${img}')"></div>`).join('')}<div class="media-placeholder">Galeria com zoom<br><small>Clique nas fotos no sistema final</small></div></div></div>
 <div class="detail-info"><span class="eyebrow">${p.type} • ${p.deal} • Código ${p.code}</span><h2>${p.title}</h2><p>⌖ ${p.location}</p><div class="card-features"><span>${p.beds} dormitórios</span><span>${p.suites} suítes</span><span>${p.baths} banheiros</span><span>${p.garage} garagem</span><span>${p.area} m²</span></div><p>${p.description}</p>
 <div class="detail-panels"><div class="detail-box"><h3>Valor e custos</h3><ul><li>Valor: ${money(p.price)}</li><li>Condomínio: ${p.condo?money(p.condo):'Não informado'}</li><li>IPTU: ${p.iptu?money(p.iptu):'Não informado'}</li><li>Corretor: ${p.broker}</li></ul></div><div class="detail-box"><h3>Características</h3><ul>${p.features.map(f=>`<li>${f}</li>`).join('')}</ul></div><div class="detail-box"><h3>Documentação</h3><p>${p.doc}</p></div><div class="detail-box"><h3>Vídeo e Tour 360°</h3><div class="media-placeholder">${p.video}<br>${p.tour}</div></div><div class="detail-box"><h3>Mapa e rota</h3><div class="map-placeholder">Mapa da região<br><small>${p.location}</small></div></div><div class="detail-box"><h3>Imóveis parecidos</h3><ul>${properties.filter(x=>x.type===p.type&&x.id!==p.id).slice(0,3).map(x=>`<li>${x.title}</li>`).join('')||'<li>Fale com Wellington para opções similares.</li>'}</ul></div></div>
 <div class="detail-actions"><a href="${whatsappText(p)}" target="_blank" rel="noopener">WhatsApp</a><button class="contact-trigger">Agendar visita</button><button class="ghost" data-share="${p.id}">Compartilhar</button><button class="ghost" data-favorite="${p.id}">${favorites.has(p.id)?'Remover favorito':'Favoritar'}</button><button class="ghost finance-trigger">Solicitar financiamento</button><a class="ghost" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(p.location)}" target="_blank" rel="noopener">Abrir rota</a></div></div>`;
 openModal(modal);
}
function showToast(t){const el=document.querySelector('#toast');el.textContent=t;el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),3200)}
function shareProperty(id){const p=properties.find(x=>x.id===id),text=`Veja este imóvel: ${p.title} (${p.code}) por ${money(p.price)}.`;if(navigator.share)navigator.share({title:p.title,text,url:location.href.split('#')[0]+'#imoveis'});else{navigator.clipboard?.writeText(text);showToast('Informações do imóvel copiadas para compartilhar.')}}

render(properties);saveFavorites();
document.addEventListener('click',e=>{
 const fav=e.target.closest('[data-favorite]');if(fav){e.stopPropagation();const id=+fav.dataset.favorite;favorites.has(id)?favorites.delete(id):favorites.add(id);saveFavorites();render(currentList,currentPage);showToast(favorites.has(id)?'Imóvel salvo nos favoritos':'Removido dos favoritos');return}
 const detail=e.target.closest('[data-detail]');if(detail){openProperty(+detail.dataset.detail);return}
 const share=e.target.closest('[data-share]');if(share){shareProperty(+share.dataset.share);return}
 const page=e.target.closest('[data-page]');if(page){render(currentList,+page.dataset.page);document.querySelector('#imoveis').scrollIntoView();return}
 if(e.target.closest('.contact-trigger')){document.querySelectorAll('.modal.open').forEach(closeModal);openModal(document.querySelector('#contactModal'))}
 if(e.target.closest('.announce-trigger')){document.querySelector('#interestSelect').value='Anunciar meu imóvel';openModal(document.querySelector('#contactModal'))}
 if(e.target.closest('.finance-trigger')){document.querySelector('#interestSelect').value='Solicitar financiamento';document.querySelectorAll('.modal.open').forEach(closeModal);openModal(document.querySelector('#contactModal'))}
 if(e.target.closest('.vic-contact')){document.querySelector('#interestSelect').value='Apartamento na planta — VIC Engenharia';document.querySelectorAll('.modal.open').forEach(closeModal);openModal(document.querySelector('#contactModal'))}
});
document.querySelector('#propertySearch').addEventListener('submit',e=>{e.preventDefault();document.querySelector('#filterCity').value=document.querySelector('#citySearch').value;document.querySelector('#filterDistrict').value=document.querySelector('#districtSearch').value;document.querySelector('#filterType').value=document.querySelector('#typeSearch').value;document.querySelector('#filterPrice').value=document.querySelector('#priceSearch').value;applyCurrentFilters();document.querySelector('#imoveis').scrollIntoView()});
document.querySelector('#advancedFilters').addEventListener('submit',e=>{e.preventDefault();applyCurrentFilters()});
document.querySelectorAll('.deal-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.deal-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentDeal=b.dataset.deal});
document.querySelectorAll('.filter-chips button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter-chips button').forEach(x=>x.classList.remove('active'));b.classList.add('active');const f=b.dataset.filter;render(f==='Todos'?properties:properties.filter(p=>p.label===f||p.label.toLowerCase()===f.toLowerCase()),1)});
document.querySelector('#showAll').onclick=()=>{currentDeal='Todos';render(properties,1)};
document.querySelectorAll('[data-quick]').forEach(b=>b.onclick=()=>{const q=b.dataset.quick;currentDeal=q==='Lançamento'?'Lançamento':q==='Na planta'?'Na planta':q==='Alugar'?'Alugar':'Comprar';render(properties.filter(p=>p.deal===currentDeal||p.label===currentDeal||p.features.includes(q)),1);document.querySelector('#imoveis').scrollIntoView()});
document.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>{render(properties.filter(p=>p.type===b.dataset.type),1);document.querySelector('#imoveis').scrollIntoView()});
document.querySelectorAll('.modal-close').forEach(b=>b.onclick=()=>closeModal(b.closest('.modal')));
document.querySelectorAll('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModal(m)}));
document.querySelector('#contactForm').onsubmit=e=>{e.preventDefault();closeModal(document.querySelector('#contactModal'));showToast('Recebemos seus dados! Wellington retornará em breve.');e.target.reset()};
document.querySelector('.favorites-trigger').onclick=()=>showFavorites();
document.querySelector('.favorites-trigger-inline').onclick=()=>showFavorites();
function showFavorites(){const list=properties.filter(p=>favorites.has(p.id));render(list,1);document.querySelector('#imoveis').scrollIntoView();showToast(list.length?`${list.length} imóvel(is) favorito(s)`:'Você ainda não salvou imóveis')}
setInterval(()=>{heroIndex=(heroIndex+1)%3;document.querySelectorAll('.hero-slide').forEach((s,i)=>s.classList.toggle('active',i===heroIndex));document.querySelectorAll('.hero-dots button').forEach((s,i)=>s.classList.toggle('active',i===heroIndex))},5000);
document.querySelectorAll('.hero-dots button').forEach((b,i)=>b.onclick=()=>{heroIndex=i;document.querySelectorAll('.hero-slide').forEach((s,j)=>s.classList.toggle('active',j===i));document.querySelectorAll('.hero-dots button').forEach((s,j)=>s.classList.toggle('active',j===i))});
document.querySelector('.menu-toggle').onclick=()=>document.querySelector('#mainNav').classList.toggle('open');
document.querySelectorAll('#mainNav a').forEach(a=>a.onclick=()=>document.querySelector('#mainNav').classList.remove('open'));
document.querySelector('#calcBtn').onclick=()=>{const value=+document.querySelector('#calcValue').value,down=+document.querySelector('#calcDown').value,months=+document.querySelector('#calcMonths').value;const financed=Math.max(value-down,0),rate=.0085,parcel=financed*(rate*Math.pow(1+rate,months))/(Math.pow(1+rate,months)-1);document.querySelector('#calcResult').textContent=`Parcela estimada: ${money(parcel||0)}`};
const plantTrack=document.querySelector('#plantCards');document.querySelector('#plantNext').onclick=()=>plantTrack.scrollBy({left:300,behavior:'smooth'});document.querySelector('#plantPrev').onclick=()=>plantTrack.scrollBy({left:-300,behavior:'smooth'});

const admin=document.querySelector('#adminModal');document.querySelector('.admin-trigger').onclick=()=>{renderAdmin('dashboard');openModal(admin)};
document.querySelectorAll('[data-admin]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-admin]').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderAdmin(b.dataset.admin)});
function renderAdmin(view){
 const c=document.querySelector('#adminContent');
 if(view==='dashboard')c.innerHTML=`<div class="admin-title"><div><span class="eyebrow">PAINEL ADMINISTRATIVO</span><h2>Olá, Wellington!</h2></div><button class="btn btn-gold" id="newProperty">+ Novo imóvel</button></div><div class="admin-metrics"><div class="metric"><span>TOTAL</span><strong>${properties.length}</strong></div><div class="metric"><span>VENDIDOS</span><strong>37</strong></div><div class="metric"><span>ALUGADOS</span><strong>54</strong></div><div class="metric"><span>VISUALIZAÇÕES</span><strong>1.842</strong></div><div class="metric"><span>LEADS</span><strong>24</strong></div></div>${propertyAdminList(properties.slice(0,5))}`;
 else if(view==='properties')c.innerHTML=`<div class="admin-title"><h2>Cadastro de imóveis</h2><button class="btn btn-gold" id="newProperty">+ Novo cadastro</button></div>${propertyAdminList(properties)}`;
 else if(view==='brokers')c.innerHTML=`<div class="admin-title"><h2>Cadastro de corretores</h2><button class="btn btn-gold">+ Corretor</button></div><div class="admin-list"><div class="admin-row"><b>Nome</b><b>CRECI</b><b>Contato</b><b>Status</b></div><div class="admin-row"><span>Wellington Nascimento</span><span>00000-F</span><span>WhatsApp • Email • Instagram</span><i class="status">ATIVO</i></div></div>`;
 else if(view==='leads')c.innerHTML=`<div class="admin-title"><h2>Leads recebidos</h2></div><div class="admin-list"><div class="admin-row"><b>Nome</b><b>Imóvel</b><b>Status/Data</b><b>Ações</b></div>${['Ana Paula|WS-254|Novo • hoje','Carlos Mendes|WS-301|Em atendimento • ontem','Camila Rocha|VIC-811|Financiamento • 2 dias'].map(x=>{const a=x.split('|');return `<div class="admin-row"><span>${a[0]}<br><small>Telefone • Email • Mensagem</small></span><span>${a[1]}</span><span><i class="status">${a[2]}</i></span><button>Responder</button></div>`}).join('')}</div>`;
 else if(view==='blog')c.innerHTML=`<div class="admin-title"><h2>Blog</h2><button class="btn btn-gold">Criar post</button></div><div class="admin-list">${['Financiamento','Na planta','Venda de imóvel'].map(cat=>`<div class="admin-row"><b>${cat}</b><span>Criar • Editar • Excluir</span><span><i class="status">PUBLICADO</i></span><button>Editar</button></div>`).join('')}</div>`;
 else if(view==='banners')c.innerHTML=`<div class="admin-title"><h2>Banners e SEO</h2></div><form class="admin-form"><label>Título SEO<input value="Wellington Silva Imóveis"></label><label>Descrição<input value="Encontre o imóvel ideal para você."></label><label>Palavras-chave<input value="imóveis, corretor, VIC Engenharia"></label><label>Open Graph<input value="Imagem de destaque"></label><label>Google Analytics<input placeholder="ID GA4"></label><label>Meta Pixel<input placeholder="ID Pixel"></label><textarea>Área para editar banners, trocar imagens e configurar sitemap.xml/robots.txt no projeto final.</textarea><button class="btn btn-gold" type="button">Salvar SEO</button></form>`;
 else if(view==='users')c.innerHTML=`<div class="admin-title"><h2>Usuários e permissões</h2></div><div class="admin-list">${['Administrador','Corretor','Editor'].map(role=>`<div class="admin-row"><b>${role}</b><span>Login • Recuperar senha</span><span><i class="status">ATIVO</i></span><button>Configurar</button></div>`).join('')}</div>`;
 else c.innerHTML=`<div class="admin-title"><h2>Configurações</h2></div><form class="admin-form"><label>Logo<input value="Wellington Silva Imóveis"></label><label>Telefone<input value="(31) 99999-9999"></label><label>WhatsApp<input value="(31) 99999-9999"></label><label>Email<input value="contato@wellingtonsilvaimoveis.com.br"></label><label>Instagram<input value="@wellingtonsilvaimoveis"></label><label>Endereço<input value="Belo Horizonte — MG"></label><textarea>Mapa, redes sociais, dados da imobiliária e integrações.</textarea><button class="btn btn-gold" type="button">Salvar configurações</button></form>`;
 const np=document.querySelector('#newProperty');if(np)np.onclick=()=>showNewPropertyForm();
}
function propertyAdminList(list){return `<div class="admin-list"><div class="admin-row"><b>Imóvel</b><b>Valor</b><b>Status</b><b>Ações</b></div>${list.map(p=>`<div class="admin-row"><span><img src="${p.images[0]}">${p.title}<br><small>${p.code} • ${p.city}/${p.district}</small></span><span>${money(p.price)}</span><span><i class="status">${p.status}</i></span><button>Editar</button></div>`).join('')}</div>`}
function showNewPropertyForm(){document.querySelector('#adminContent').innerHTML=`<div class="admin-title"><h2>Criar novo anúncio</h2></div><form class="admin-form" id="newPropertyForm"><label>Título<input required placeholder="Título"></label><label>Código<input placeholder="Código"></label><label>Tipo<select><option>Apartamento</option><option>Casa</option><option>Terreno</option><option>Comercial</option></select></label><label>Finalidade<select><option>Comprar</option><option>Alugar</option><option>Lançamento</option><option>Na planta</option></select></label><label>Preço<input type="number"></label><label>Condomínio<input type="number"></label><label>IPTU<input type="number"></label><label>Cidade<input></label><label>Bairro<input></label><label>CEP<input></label><label>Endereço<input></label><label>Área<input></label><label>Área construída<input></label><label>Quartos<input></label><label>Suítes<input></label><label>Banheiros<input></label><label>Garagem<input></label><label>Status<select><option>Publicado</option><option>Vendido</option><option>Alugado</option><option>Rascunho</option></select></label><label>Vídeo<input></label><label>Tour 360<input></label><label>Planta<input></label><label>Fotos<input type="file" multiple></label><textarea placeholder="Descrição e características"></textarea><button class="btn btn-gold" type="submit">Publicar anúncio →</button></form>`;document.querySelector('#newPropertyForm').onsubmit=e=>{e.preventDefault();renderAdmin('properties');showToast('Anúncio publicado com sucesso!')}}
